version: 2

# Options de configuration
build:
  image: latest  # L'image du générateur de documentation à utiliser
  python:
    install:
    - requirements: Documentation Prooftag/requirements.txt
    - requirements: requirements.txt
    version: 3.8  # Version de Python à utiliser

formats:       # Formats à générer
  - htmlzip
  - pdf
  - epub
